"""scope factory stock and production by quantity

Revision ID: 0ac42313c6e8
Revises: 75f33f44ef1c
Create Date: 2026-09-15 22:22:19.333080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac42313c6e8'
down_revision: Union[str, Sequence[str], None] = '75f33f44ef1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factory_current_stock', sa.Column('quantity_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_factory_current_stock_product_id'), table_name='factory_current_stock')
    op.create_index(op.f('ix_factory_current_stock_product_id'), 'factory_current_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_factory_current_stock_quantity_id'), 'factory_current_stock', ['quantity_id'], unique=False)
    op.create_unique_constraint('uq_factory_current_stock_slot', 'factory_current_stock', ['product_id', 'quantity_id'])
    op.create_foreign_key(None, 'factory_current_stock', 'quantities', ['quantity_id'], ['id'])
    op.add_column('production_records', sa.Column('quantity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_production_records_quantity_id'), 'production_records', ['quantity_id'], unique=False)
    op.create_foreign_key(None, 'production_records', 'quantities', ['quantity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_records', type_='foreignkey')
    op.drop_index(op.f('ix_production_records_quantity_id'), table_name='production_records')
    op.drop_column('production_records', 'quantity_id')
    op.drop_constraint(None, 'factory_current_stock', type_='foreignkey')
    op.drop_constraint('uq_factory_current_stock_slot', 'factory_current_stock', type_='unique')
    op.drop_index(op.f('ix_factory_current_stock_quantity_id'), table_name='factory_current_stock')
    op.drop_index(op.f('ix_factory_current_stock_product_id'), table_name='factory_current_stock')
    op.create_index(op.f('ix_factory_current_stock_product_id'), 'factory_current_stock', ['product_id'], unique=True)
    op.drop_column('factory_current_stock', 'quantity_id')
    # ### end Alembic commands ###
