"""add depot module tables

Revision ID: 19a4d7b3e882
Revises: 37fe14b63113
Create Date: 2026-09-12 13:51:04.445048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a4d7b3e882'
down_revision: Union[str, Sequence[str], None] = '37fe14b63113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('sold_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quantity_id'], ['quantities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depot_id', 'product_id', 'quantity_id', 'sale_date', name='uq_current_sales_slot')
    )
    op.create_index(op.f('ix_current_sales_depot_id'), 'current_sales', ['depot_id'], unique=False)
    op.create_index(op.f('ix_current_sales_product_id'), 'current_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_current_sales_quantity_id'), 'current_sales', ['quantity_id'], unique=False)
    op.create_index(op.f('ix_current_sales_sale_date'), 'current_sales', ['sale_date'], unique=False)
    op.create_table('current_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_id', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quantity_id'], ['quantities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depot_id', 'product_id', 'quantity_id', name='uq_current_stock_slot'),
    sa.CheckConstraint('current_amount >= 0', name='ck_current_stock_non_negative')
    )
    op.create_index(op.f('ix_current_stock_depot_id'), 'current_stock', ['depot_id'], unique=False)
    op.create_index(op.f('ix_current_stock_product_id'), 'current_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_current_stock_quantity_id'), 'current_stock', ['quantity_id'], unique=False)
    op.create_table('restock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_history_id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_id', sa.Integer(), nullable=False),
    sa.Column('quantity_delivered', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'rejected', name='restock_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('restock_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quantity_id'], ['quantities.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['supply_history_id'], ['supply_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restock_history_depot_id'), 'restock_history', ['depot_id'], unique=False)
    op.create_index(op.f('ix_restock_history_product_id'), 'restock_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_restock_history_quantity_id'), 'restock_history', ['quantity_id'], unique=False)
    op.create_index(op.f('ix_restock_history_supply_history_id'), 'restock_history', ['supply_history_id'], unique=False)
    op.create_table('sales_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('amount_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sold_by_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sale_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quantity_id'], ['quantities.id'], ),
    sa.ForeignKeyConstraint(['sold_by_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_history_depot_id'), 'sales_history', ['depot_id'], unique=False)
    op.create_index(op.f('ix_sales_history_product_id'), 'sales_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_history_quantity_id'), 'sales_history', ['quantity_id'], unique=False)
    op.create_index(op.f('ix_sales_history_sale_date'), 'sales_history', ['sale_date'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
    CREATE OR REPLACE FUNCTION fn_apply_restock_effect() RETURNS TRIGGER AS $$
    BEGIN
        IF TG_OP = 'INSERT' THEN
            IF NEW.status = 'confirmed' THEN
                INSERT INTO current_stock (depot_id, product_id, quantity_id, current_amount, updated_at)
                VALUES (NEW.depot_id, NEW.product_id, NEW.quantity_id, NEW.quantity_delivered, now())
                ON CONFLICT (depot_id, product_id, quantity_id)
                DO UPDATE SET current_amount = current_stock.current_amount + NEW.quantity_delivered, updated_at = now();
            END IF;
            RETURN NEW;
        ELSIF TG_OP = 'UPDATE' THEN
            IF OLD.status = 'confirmed' THEN
                UPDATE current_stock
                SET current_amount = current_amount - OLD.quantity_delivered, updated_at = now()
                WHERE depot_id = OLD.depot_id AND product_id = OLD.product_id AND quantity_id = OLD.quantity_id;
            END IF;
            IF NEW.status = 'confirmed' THEN
                INSERT INTO current_stock (depot_id, product_id, quantity_id, current_amount, updated_at)
                VALUES (NEW.depot_id, NEW.product_id, NEW.quantity_id, NEW.quantity_delivered, now())
                ON CONFLICT (depot_id, product_id, quantity_id)
                DO UPDATE SET current_amount = current_stock.current_amount + NEW.quantity_delivered, updated_at = now();
            END IF;
            RETURN NEW;
        ELSIF TG_OP = 'DELETE' THEN
            IF OLD.status = 'confirmed' THEN
                UPDATE current_stock
                SET current_amount = current_amount - OLD.quantity_delivered, updated_at = now()
                WHERE depot_id = OLD.depot_id AND product_id = OLD.product_id AND quantity_id = OLD.quantity_id;
            END IF;
            RETURN OLD;
        END IF;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trg_restock_history_effect
    AFTER INSERT OR UPDATE OR DELETE ON restock_history
    FOR EACH ROW EXECUTE FUNCTION fn_apply_restock_effect();
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION fn_apply_sale_effect() RETURNS TRIGGER AS $$
    DECLARE
        rows_affected INTEGER;
    BEGIN
        IF TG_OP = 'INSERT' THEN
            UPDATE current_stock
            SET current_amount = current_amount - NEW.quantity_sold, updated_at = now()
            WHERE depot_id = NEW.depot_id AND product_id = NEW.product_id AND quantity_id = NEW.quantity_id
              AND current_amount >= NEW.quantity_sold;
            GET DIAGNOSTICS rows_affected = ROW_COUNT;
            IF rows_affected = 0 THEN
                RAISE EXCEPTION 'insufficient_stock: depot % product % quantity % has insufficient stock for a sale of %', NEW.depot_id, NEW.product_id, NEW.quantity_id, NEW.quantity_sold;
            END IF;

            INSERT INTO current_sales (depot_id, product_id, quantity_id, sale_date, quantity_sold, sold_amount)
            VALUES (NEW.depot_id, NEW.product_id, NEW.quantity_id, NEW.sale_date, NEW.quantity_sold, NEW.amount_sold)
            ON CONFLICT (depot_id, product_id, quantity_id, sale_date)
            DO UPDATE SET quantity_sold = current_sales.quantity_sold + NEW.quantity_sold,
                          sold_amount = current_sales.sold_amount + NEW.amount_sold;
            RETURN NEW;

        ELSIF TG_OP = 'UPDATE' THEN
            UPDATE current_stock
            SET current_amount = current_amount + OLD.quantity_sold, updated_at = now()
            WHERE depot_id = OLD.depot_id AND product_id = OLD.product_id AND quantity_id = OLD.quantity_id;

            UPDATE current_sales
            SET quantity_sold = quantity_sold - OLD.quantity_sold,
                sold_amount = sold_amount - OLD.amount_sold
            WHERE depot_id = OLD.depot_id AND product_id = OLD.product_id AND quantity_id = OLD.quantity_id AND sale_date = OLD.sale_date;

            UPDATE current_stock
            SET current_amount = current_amount - NEW.quantity_sold, updated_at = now()
            WHERE depot_id = NEW.depot_id AND product_id = NEW.product_id AND quantity_id = NEW.quantity_id
              AND current_amount >= NEW.quantity_sold;
            GET DIAGNOSTICS rows_affected = ROW_COUNT;
            IF rows_affected = 0 THEN
                RAISE EXCEPTION 'insufficient_stock: depot % product % quantity % has insufficient stock for updated sale of %', NEW.depot_id, NEW.product_id, NEW.quantity_id, NEW.quantity_sold;
            END IF;

            INSERT INTO current_sales (depot_id, product_id, quantity_id, sale_date, quantity_sold, sold_amount)
            VALUES (NEW.depot_id, NEW.product_id, NEW.quantity_id, NEW.sale_date, NEW.quantity_sold, NEW.amount_sold)
            ON CONFLICT (depot_id, product_id, quantity_id, sale_date)
            DO UPDATE SET quantity_sold = current_sales.quantity_sold + NEW.quantity_sold,
                          sold_amount = current_sales.sold_amount + NEW.amount_sold;
            RETURN NEW;

        ELSIF TG_OP = 'DELETE' THEN
            UPDATE current_stock
            SET current_amount = current_amount + OLD.quantity_sold, updated_at = now()
            WHERE depot_id = OLD.depot_id AND product_id = OLD.product_id AND quantity_id = OLD.quantity_id;

            UPDATE current_sales
            SET quantity_sold = quantity_sold - OLD.quantity_sold,
                sold_amount = sold_amount - OLD.amount_sold
            WHERE depot_id = OLD.depot_id AND product_id = OLD.product_id AND quantity_id = OLD.quantity_id AND sale_date = OLD.sale_date;
            RETURN OLD;
        END IF;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trg_sales_history_effect
    AFTER INSERT OR UPDATE OR DELETE ON sales_history
    FOR EACH ROW EXECUTE FUNCTION fn_apply_sale_effect();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_sales_history_effect ON sales_history;")
    op.execute("DROP FUNCTION IF EXISTS fn_apply_sale_effect();")
    op.execute("DROP TRIGGER IF EXISTS trg_restock_history_effect ON restock_history;")
    op.execute("DROP FUNCTION IF EXISTS fn_apply_restock_effect();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_history_sale_date'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_quantity_id'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_product_id'), table_name='sales_history')
    op.drop_index(op.f('ix_sales_history_depot_id'), table_name='sales_history')
    op.drop_table('sales_history')
    op.drop_index(op.f('ix_restock_history_supply_history_id'), table_name='restock_history')
    op.drop_index(op.f('ix_restock_history_quantity_id'), table_name='restock_history')
    op.drop_index(op.f('ix_restock_history_product_id'), table_name='restock_history')
    op.drop_index(op.f('ix_restock_history_depot_id'), table_name='restock_history')
    op.drop_table('restock_history')
    op.drop_index(op.f('ix_current_stock_quantity_id'), table_name='current_stock')
    op.drop_index(op.f('ix_current_stock_product_id'), table_name='current_stock')
    op.drop_index(op.f('ix_current_stock_depot_id'), table_name='current_stock')
    op.drop_table('current_stock')
    op.drop_index(op.f('ix_current_sales_sale_date'), table_name='current_sales')
    op.drop_index(op.f('ix_current_sales_quantity_id'), table_name='current_sales')
    op.drop_index(op.f('ix_current_sales_product_id'), table_name='current_sales')
    op.drop_index(op.f('ix_current_sales_depot_id'), table_name='current_sales')
    op.drop_table('current_sales')
    # ### end Alembic commands ###
