"""baseline: existing schema

Revision ID: 37fe14b63113
Revises: 
Create Date: 2026-09-12 13:49:16.908881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fe14b63113'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factory_stock_product_id'), table_name='factory_current_stock')
    op.create_index(op.f('ix_factory_current_stock_product_id'), 'factory_current_stock', ['product_id'], unique=True)
    op.create_index(op.f('ix_supply_history_product_id'), 'supply_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_supply_history_quantity_id'), 'supply_history', ['quantity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_history_quantity_id'), table_name='supply_history')
    op.drop_index(op.f('ix_supply_history_product_id'), table_name='supply_history')
    op.drop_index(op.f('ix_factory_current_stock_product_id'), table_name='factory_current_stock')
    op.create_index(op.f('ix_factory_stock_product_id'), 'factory_current_stock', ['product_id'], unique=True)
    # ### end Alembic commands ###
