"""restore id primary key on prices, keep amount as integer

Revision ID: 75f33f44ef1c
Revises: f658f707e56f
Create Date: 2026-09-12 17:03:20.319870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f33f44ef1c'
down_revision: Union[str, Sequence[str], None] = 'f658f707e56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The team settled on: id as the primary key, quantity_id unique,
    # amount as a plain integer (no sub-unit currency in practice).
    # Written defensively since this table's structure has been flipped
    # more than once by concurrent, uncoordinated manual changes.
    op.execute("ALTER TABLE prices DROP CONSTRAINT IF EXISTS prices_pkey")
    op.execute("ALTER TABLE prices ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY")
    op.execute("ALTER TABLE prices ADD PRIMARY KEY (id)")
    op.execute(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_prices_quantity_id') THEN "
        "ALTER TABLE prices ADD CONSTRAINT uq_prices_quantity_id UNIQUE (quantity_id); "
        "END IF; END $$;"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE prices DROP CONSTRAINT IF EXISTS uq_prices_quantity_id")
    op.execute("ALTER TABLE prices DROP CONSTRAINT IF EXISTS prices_pkey")
    op.execute("ALTER TABLE prices DROP COLUMN IF EXISTS id")
    op.execute("ALTER TABLE prices ADD PRIMARY KEY (quantity_id)")
