"""add depot_id and supplier_id to supply history

Revision ID: 8ebb38323331
Revises: fca0b3ac01fc
Create Date: 2026-09-16 14:36:36.763877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebb38323331'
down_revision: Union[str, Sequence[str], None] = 'fca0b3ac01fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supply_history', sa.Column('depot_id', sa.Integer(), nullable=True))
    op.add_column('supply_history', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_supply_history_depot_id'), 'supply_history', ['depot_id'], unique=False)
    op.create_index(op.f('ix_supply_history_supplier_id'), 'supply_history', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'supply_history', 'personnel', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'supply_history', 'depots', ['depot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supply_history', type_='foreignkey')
    op.drop_constraint(None, 'supply_history', type_='foreignkey')
    op.drop_index(op.f('ix_supply_history_supplier_id'), table_name='supply_history')
    op.drop_index(op.f('ix_supply_history_depot_id'), table_name='supply_history')
    op.drop_column('supply_history', 'supplier_id')
    op.drop_column('supply_history', 'depot_id')
    # ### end Alembic commands ###
